version: "3"

services:
  backend:
    build: ./
    container_name: shop_sound_cont
    working_dir: /shop_sound
    command:
      - /commands/start_server.sh
    ports:
      - 8080:8008
    volumes:
      - ./src/:/shop_sound
    env_file:
      - .env

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg_data: { }

# docker run --rm -d -p 8080:8008 -v `pwd`/src:/shop_sound --name shop_sound_cont shop_sound /commands/start_server.sh
