version: "3"

services:

  postgres:
    image: postgres:12
    expose:
      - 5432
    restart: always
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - 5000:80

    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  backend:
    build: ./
    container_name: shop_sound_cont
    working_dir: /shop_sound
    command:
      - /commands/start_server.sh
    ports:
      - 8080:8000
    volumes:
      - ./src/:/shop_sound
      - ./commands:/commands
    env_file:
      - .env
    depends_on:
     - postgres

  mongodb:
    image: mongo:3-stretch
    container_name: mongodb_container
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    command: ["--bind_ip_all", "--smallfiles"]
    env_file:
      - .env

  mongoadmin:
    image: mongo-express
    restart: always
    container_name: mongo_admin_container
    ports:
      - 8091:8081
    env_file:
      - .env
    links:
      - mongodb
    depends_on:
      - mongodb

volumes:
  local_postgres_data:
  local_postgres_data_backups:
  pgadmin_data:
  mongo_data:

