# Generated by Django 4.1.1 on 2022-09-26 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, null=True)),
                (
                    "image",
                    models.ImageField(
                        default="static/image/products/non-image.png",
                        null=True,
                        upload_to="static/image/products/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("seo_title", models.CharField(max_length=100, null=True)),
                ("seo_description", models.CharField(max_length=300, null=True)),
                ("seo_text", models.TextField(max_length=5000, null=True)),
                (
                    "image",
                    models.ImageField(
                        default="static/image/category/non-image.png",
                        null=True,
                        upload_to="static/image/category/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("seo_title", models.CharField(max_length=100, null=True)),
                ("seo_description", models.CharField(max_length=300, null=True)),
                ("seo_text", models.TextField(max_length=5000, null=True)),
                (
                    "image",
                    models.ImageField(
                        default="static/image/sub-category/non-image.png",
                        null=True,
                        upload_to="static/image/sub-category/",
                    ),
                ),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, null=True)),
                (
                    "image",
                    models.ImageField(
                        default="static/image/products/non-image.png",
                        null=True,
                        upload_to="static/image/products/",
                    ),
                ),
                ("price", models.SmallIntegerField(null=True)),
                ("description", models.TextField(max_length=1500, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.brand"
                    ),
                ),
                ("order", models.ManyToManyField(to="shop.order")),
                (
                    "sub_category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.subcategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(related_name="product", to="shop.product"),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
