# Generated by Django 4.1.1 on 2022-10-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
        migrations.AddField(
            model_name="product",
            name="availability",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
