# Generated by Django 4.1.1 on 2022-09-26 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(related_name="orders", to="shop.product"),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand",
                to="shop.brand",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_category",
                to="shop.subcategory",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="shop.category",
            ),
        ),
    ]
