# Generated by Django 4.1.1 on 2022-10-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="alias",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
