# Generated by Django 4.1.1 on 2022-10-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_subcategory_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="alias",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
