# Generated by Django 4.1.1 on 2022-09-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_order_products_alter_product_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.SmallIntegerField(null=True),
        ),
    ]
