# Generated by Django 4.1.1 on 2022-10-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_brand_id_alter_category_id_alter_order_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pages",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.BooleanField(default=True, null=True)),
                ("seo_title", models.CharField(max_length=100, null=True)),
                ("seo_description", models.CharField(max_length=300, null=True)),
                ("name", models.CharField(max_length=150, null=True)),
                ("h1", models.CharField(max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Static page",
                "verbose_name_plural": "Static pages",
            },
        ),
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.ImageField(
                default="media/image/products/non-image.png",
                null=True,
                upload_to="media/image/products/",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                default="media/image/category/non-image.png",
                null=True,
                upload_to="media/image/category/",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(blank=True, null=True, related_name="products", to="shop.product"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="media/image/products/non-image.png",
                null=True,
                upload_to="media/image/products/",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(
                default="media/image/sub-category/non-image.png",
                null=True,
                upload_to="media/image/sub-category/",
            ),
        ),
    ]
