# Generated by Django 4.1.1 on 2022-09-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_order_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="orders", to="shop.product"
            ),
        ),
    ]
