# Generated by Django 4.1.1 on 2022-10-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_brand_image_alter_category_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.ImageField(default="image/non-image.png", null=True, upload_to="image/products/"),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(default="image/non-image.png", null=True, upload_to="image/category/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default="image/non-image.png", null=True, upload_to="image/products/"),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(
                default="image/non-image.png",
                null=True,
                upload_to="media/image/sub-category/",
            ),
        ),
    ]
