# Generated by Django 4.1.1 on 2022-09-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_order_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="order",
        ),
    ]
