# Generated by Django 4.1.1 on 2022-09-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_remove_product_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_time_create",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="date_time_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[("UAH", "UAH"), ("USD", "USD")], default="UAH", max_length=3
            ),
        ),
    ]
