# Generated by Django 4.1.1 on 2022-11-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_brand_image_alter_category_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default="image/non-image.png", null=True, upload_to="image/products/"),
        ),
    ]
