# Generated by Django 4.1.1 on 2022-11-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.ImageField(
                default="static/images/non-image.png",
                null=True,
                upload_to="media/image/products/",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                default="static/images/non-image.png",
                null=True,
                upload_to="media/image/category/",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="static/images/non-image.png",
                null=True,
                upload_to="image/products/",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(
                default="static/images/non-image.png",
                null=True,
                upload_to="media/image/sub-category/",
            ),
        ),
    ]
