# Generated by Django 4.1.1 on 2022-11-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_brand_image_alter_category_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="url",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
