# Generated by Django 4.1.1 on 2022-09-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_order_order_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_num",
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
