# Generated by Django 4.1.1 on 2022-09-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_alter_order_order_num"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AddField(
            model_name="brand",
            name="index",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="seo_description",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="seo_title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="index",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="index",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_description",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="index",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
