# Generated by Django 4.1.1 on 2022-11-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_alter_product_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
