# Generated by Django 4.1.1 on 2022-11-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_product_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="alias",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
