# Generated by Django 4.1.1 on 2022-11-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_remove_order_user_orderitem_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="top_item",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
