# Generated by Django 4.1.1 on 2022-10-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customers",
            name="is_content",
            field=models.BooleanField(
                default=False,
                help_text="Only for content managers",
                verbose_name="content_manager",
            ),
        ),
    ]
