# Generated by Django 4.1.1 on 2022-10-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customers_is_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
